worker_processes 1;
events { worker_connections 1024; }
http {
    include mime.types;
    default_type application/octet-stream;
    server {
        listen 80;
        server_name localhost;
        server_tokens off;
        
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
        
        # Ensure PCAP is served correctly
        location = /capture.pcap {
            root /usr/share/nginx/html;
            add_header Content-Disposition 'attachment; filename="capture.pcap"';
        }
    }
}
